const FOOTER_DATA = {
  Services: [
    { text: "Premium Domains For Sale", link: "https://google.com" },
    { text: "Ultra Premium Marketplace", link: "https://google.com" },
    { text: "Naming Contest", link: "https://google.com" },
    { text: "Brandable Domains", link: "https://google.com" },
    { text: ".ai Domains", link: "https://google.com" },
    { text: "Short Domains", link: "https://google.com" },
    { text: "3 Letter Domains", link: "https://google.com" },
    { text: "4 Letter Domains", link: "https://google.com" },
    { text: "5 Letter Domains", link: "https://google.com" },
    { text: "6 Letter Domains", link: "https://google.com" },
    { text: "7 Letter Domains", link: "https://google.com" },
    { text: "One Word Domains", link: "https://google.com" },
    { text: "Aged Domains", link: "https://google.com" },
    { text: "Aftermarket Domains", link: "https://google.com" },
    { text: "Expired Domains", link: "https://google.com" },
    { text: ".in Domains", link: "https://google.com" },
    { text: ".ca Domains", link: "https://google.com" },
    { text: ".co.uk Domains", link: "https://google.com" },
    { text: ".de Domains", link: "https://google.com" },
    { text: "Domains for Rent", link: "https://google.com" },
    { text: "Domain Broker", link: "https://google.com" },
    { text: "Domain Marketplace", link: "https://google.com" },
    { text: "Brand Identity Design", link: "https://google.com" },
    { text: "Brand Naming Agency", link: "https://google.com" },
    { text: "Logo Contests", link: "https://google.com" },
    { text: "Tagline Contests", link: "https://google.com" },
    { text: "Audience Research", link: "https://google.com" },
  ],
  Tools: [
    { text: "Business Name Generator", link: "https://google.com" },
    { text: "Domain Name Generator", link: "https://google.com" },
    { text: "Domain Appraisal", link: "https://google.com" },
    { text: "How to Name Your Business", link: "https://google.com" },
    { text: "Startup Toolkit", link: "https://google.com" },
    { text: "Startup Name Generator", link: "https://google.com" },
    { text: "Band Name Generator", link: "https://google.com" },
    { text: "Blog Name Generator", link: "https://google.com" },
    { text: "Product Name Generator", link: "https://google.com" },
    { text: "YouTube Name Generator", link: "https://google.com" },
    { text: "Domain Extensions", link: "https://google.com" },
    { text: "WHOIS Lookup", link: "https://google.com" },
    { text: "Build a Brand", link: "https://google.com" },
    { text: "AI Logo Generator", link: "https://google.com" },
  ],
  Trademarks: [
    { text: "Trademark", link: "https://google.com" },
    { text: "Trademark Filing", link: "https://google.com" },
    { text: "Premium Trademark Reports", link: "https://google.com" },
    { text: "Brand Monitoring", link: "https://google.com" },
    { text: "Free Trademark Checker", link: "https://google.com" },
  ],
  Sellers: [
    { text: "Become a Seller", link: "https://google.com" },
    { text: "Domain Selling Info", link: "https://google.com" },
    { text: "Ultra Premium Seller Info", link: "https://google.com" },
    { text: "Sapphire Marketplace", link: "https://google.com" },
    { text: "ccTLD Marketplace", link: "https://google.com" },
    { text: "Domain Auctions", link: "https://google.com" },
    { text: "Discussion Forum", link: "https://google.com" },
  ],
  Creatives: [
    { text: "Become a Creative", link: "https://google.com" },
    { text: "Creative FAQs", link: "https://google.com" },
    { text: "Active Contests", link: "https://google.com" },
    { text: "Recent Winners", link: "https://google.com" },
    { text: "Discussion Forum", link: "https://google.com" },
  ],
  Atom: [
    { text: "About", link: "https://google.com" },
    { text: "Contact", link: "https://google.com" },
    { text: "How It Works", link: "https://google.com" },
    { text: "Testimonials", link: "https://google.com" },
    { text: "Our Work", link: "https://google.com" },
    { text: "Help & FAQs", link: "https://google.com" },
    { text: "Partner with Us", link: "https://google.com" },
    { text: "Affiliate Program", link: "https://google.com" },
    { text: "AtomRadar", link: "https://google.com" },
    { text: "Blog", link: "https://google.com" },
    { text: "Careers", link: "https://google.com" },
  ],
  Legal: [
    { text: "Terms of Service", link: "https://google.com" },
    { text: "Privacy Policy", link: "https://google.com" },
    { text: "Cookie Policy", link: "https://google.com" },
  ],
};

export default FOOTER_DATA;
