POST http://localhost:5000/offers/moderator-list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjEwLCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJUZXN0IiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6Im1vZGVyYXRvciIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTk5OTg1MzEsImV4cCI6MTc2MDAwMjEzMX0.y7hnzXo4H8x4w8Ma0cPJToQmNYYxYfKoMtJhWeLjqhM

{
  "page": 1
}

POST http://localhost:5000/offers/approve
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjEwLCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJUZXN0IiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6Im1vZGVyYXRvciIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTk5OTg1MzEsImV4cCI6MTc2MDAwMjEzMX0.y7hnzXo4H8x4w8Ma0cPJToQmNYYxYfKoMtJhWeLjqhM

POST http://localhost:5000/offers/reject
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjEwLCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJUZXN0IiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6Im1vZGVyYXRvciIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTk5OTg1MzEsImV4cCI6MTc2MDAwMjEzMX0.y7hnzXo4H8x4w8Ma0cPJToQmNYYxYfKoMtJhWeLjqhM

POST http://localhost:5000/offers/my
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjEwLCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJUZXN0IiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6Im1vZGVyYXRvciIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTk5OTg1MzEsImV4cCI6MTc2MDAwMjEzMX0.y7hnzXo4H8x4w8Ma0cPJToQmNYYxYfKoMtJhWeLjqhM